#mongo.uri = mongodb+srv://srd22:KsfM04LnO5aIs7Y9@cloudcostcluster.bzdenas.mongodb.net/?appName=CloudCostCluster
#mongo.db = cloudcostdb
#mongo.collection = azurecosts


USN = srd22
PWD = KsfM04LnO5aIs7Y9
SERVER = cloudcostcluster.bzdenas
DB = cloudcostdb
COLLECTION = azurecosts
